### ISSUE TITLE
Properties not tracked if not set at construction

### ISSUE THREAD

**Issue by rpggio** [gabeklein/expressive-mvc#17]
If an optional prop is not set when controller is constructed, the prop is not tracked.
Workaround: Initialize prop with `undefined`.

https://codesandbox.io/s/react-use-controller-bug-report-nullable-prop-ttzop

**Comment by gabeklein** [comment]
Thanks for filing the issue!

So really, just because of how javascript works, this is somewhat impossible to fix. (At least until [Proxies](https://hackernoon.com/introducing-javascript-es6-proxies-1327419ab413) go mainstream).

During development and ideation, this was one of the most fundamental limitations of `use-controller` however eventually, I did come to the conclusion it was not a big deal. Technically, where properties are tracked like this, being clear on what is or isn't going to trigger a render can be very important. It would be something of an anti-pattern to act on properties which were not initialised at construction. Even [TypeScript will enforce this](https://stackoverflow.com/questions/54104187/typescript-complain-has-no-initializer-and-is-not-definitely-assigned-in-the-co/54104796) in strict-mode for _any_ given class.

That said I would say it's better to simply define tracked properties as `undefined` as you said. As your controllers get bigger and more complex, it will start to be helpful in predicting the behaviour of your renders.

**Comment by gabeklein** [comment]
If you ever do want to track a property after the fact though, you can! 

The controller API does support this [with the `add()` method](https://github.com/gabeklein/use-controller#addkey-string-value-any-boolean). Call this at any point to register a new key for live-tracking.

**Comment by ryascl** [comment]
Thanks @gabeklein ! This library is a great idea.

A side question:
We are separating our controlled components from view (presentation) components, so the view components can be mocked in Storybook.
Is this the easiest way to wire them? It seems the destructure is required in controlled component, even though the view component already destructures. 
`
export function Doodad() {
  const {a, b, c} = DoodadController.use()
  return React.createElement(DoodadView, {a, b, c})
}

export function DoodadView({a, b, c}) {
  return <div>Values: {a}, {b}, {c}</div>
}
`

**Comment by gabeklein** [comment]
@ryascl I appreciate you like it! 

Let's though keep side-chatter off the issue thread. My email is public on GitHub profile, email me there if you'd like advice!
