### ISSUE TITLE
initial state

### ISSUE THREAD

**Issue by dferber90** [gabeklein/expressive-mvc#50]
I stumbled upon this library and got intrigued. Seems pretty nice!

How would a react component set initial state for the model?

Let's say I want to initialize the counter to props.value

```
import Model from "@expressive/react";

class Counter extends Model {
  current = 1;

  increment = () => this.current++;
  decrement = () => this.current--;
}

export default SomeComponent(props) => {
  // ❓ how do I make Counter.use() init to props.initialValue? or just to a given number like 5?
  const { current, increment, decrement } = Counter.use(); 

  return (
    <div>
      <button onClick={decrement}>{"-"}</button>
      <pre>{current}</pre>
      <button onClick={increment}>{"+"}</button>
    </div>
  );
};
```

The only way I could think of would be to provide it with the default values through an `useEffect` call.

**Comment by gabeklein** [comment]
Hey! Great question, yes this is possible but hadn't been documented so I will demonstrate here.

The function `use` has an overload which allows you pass props either directly or indirectly into the model. Consider the following.

```ts
class Example extends Model {
  foo?: number = undefined;
  bar?: number = undefined;
}

const example = Example.use({ foo: 1, bar: 2, baz: 3 });
```

Here `use` will transfer `foo` and `bar` to Example because they exist on that model. `baz` however is not because it is not "part of the model". That is determined by a property having any explicit starting value - even if it's `undefined`. This way you can have either a default value, or simply rely on the external value.

There are also ways to enforce a value comes from outside (or it throws), however that involves using a concept of instructions which are not yet documented greatly. 😬 More on that soon!

Here's a code sandbox which goes into this feature in more depth!
https://codesandbox.io/s/example-use-props-75mvm

**Comment by dferber90** [comment]
Cool, that works! I think I made it that far in my own tests, but got stuck trying to update a value which comes in as an initial value. Maybe I am too used to thinking in `useState()`?

I amended the demo with

```tsx
class Greetings extends Model {
  changeName = () => {
    console.log("changeName called");
    this.name = "Joe";
  };

  // ....
}


// and later
      <button type="button" onClick={changeName}>
        set name
      </button>
```

But the displayed name never updates when I press the button. It seems like the passed in props will always overwrite the model's state?

CodeSandbox here https://codesandbox.io/s/example-use-props-forked-9b4gzr?file=/src/App.js:155-601

---

What I ended up doing instead is not passing any `props` but rather using an effect to init the model

```tsx
const { firstName, isBirthday, changeName, init } = Greetings.use(/* no props passed here */);
useEffect(() => { init(props.foo) /* call init so the model can set itself up once */ }, [props.foo])
```

A more out of the box way of doing this would be super convenient if here isn't one yet <picture data-single-emoji=":blob_smile:" title=":blob_smile:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..WoeQj4tEavlJrnGp.d0wjEhT-BEqVCnJBMNxW0lFbfOiTmvIGRcrX2fgSrUsMdUy0oyddCV33qIqJI-zhEaSbymt8U2vPIAI27nyebLWj0B8afBuPaRRjIwbCuWGbVtrt3xikMK34zSk.hoqyQucRf4wlflgiYv_fTw" alt=":blob_smile:" align="absmiddle"></picture>

**Comment by gabeklein** [comment]
@dferber90 Point taken!

`Model.use(props)` will now apply only **once** by default, on the initial render. A new overload has also been added, to persistently apply every render. `Model.use(props, true)` will do so - as you pointed out, this would interfere with updating values. So, use this in scenarios where the properties are `readonly` and intended to come from outside (prop driven).
